### ISSUE TITLE
Update Conclave Insurance Procedures and Transmittal Forms

### ISSUE THREAD

**Issue by blove** [OAWest/western.oa-bsa.org#112]
Update forms available on website at: http://western.oa-bsa.org/resources/sections.html

[OA Insurance Procedures Updated 3-31-2017.docx](https://github.com/OAWest/western.oa-bsa.org/files/913476/OA.Insurance.Procedures.Updated.3-31-2017.docx)
[Conclave Insurance Payment Transmittal Updated 3-31-2017.docx](https://github.com/OAWest/western.oa-bsa.org/files/913477/Conclave.Insurance.Payment.Transmittal.Updated.3-31-2017.docx)

Use the fillable PDF for the transmittal:
[2017-conclave-insurance-payment-transmittal-fillable.pdf](https://github.com/OAWest/western.oa-bsa.org/files/913717/2017-conclave-insurance-payment-transmittal-fillable.pdf)

**Comment by MacRichards** [comment]
Fixed in pull #113

**Comment by blove** [comment]
Guys, here is the PDF for the procedures document:

[OA.Insurance.Procedures.Updated.3-31-2017.pdf](https://github.com/OAWest/western.oa-bsa.org/files/918480/OA.Insurance.Procedures.Updated.3-31-2017.pdf)

**Comment by blove** [comment]
I see now in your PR that you already converted the docx to pdf. Thanks, I'll get this pushed to the website.
