### ISSUE TITLE
Update NLS & DYLC pages for 2018 training events & registration

### ISSUE THREAD

**Issue by rjrosamond** [OAWest/western.oa-bsa.org#138]
Please update the [NLS](http://western.oa-bsa.org/program/training/nls/) and [DYLC](http://western.oa-bsa.org/program/training/dylc/) pages with the following info common to both pages:

<b>Replace the 2017 dates with the following:</b>

## April 13-15, 2018 - Los Angeles
- NLS & DYLC
- Price: $210
- [Register](https://registration.oa-bsa.org/Event/44)
- [Hubert Eaton Scout Reservation - Cedar Glen, CA](https://www.glaacbsa.org/Hubert_Eaton)
- [Required: Medical Form Part A & B](http://www.scouting.org/filestore/HealthSafety/pdf/680-001_AB.pdf)

## October 12-14, 2018 - Denver/Colorado Springs
- NLS & DYLC
- Price: $230
- [Register](https://registration.oa-bsa.org/Event/45)
- [Ponderosa Retreat & Conference Center - Larkspur, CO](http://visitponderosa.com/)
- [Required: Medical Form Part A & B](http://www.scouting.org/filestore/HealthSafety/pdf/680-001_AB.pdf)

## November 16-18, 2018 - Lake Tahoe
- NLS & DYLC
- Price: $275 (Friday dinner included)
- [Register](https://registration.oa-bsa.org/Event/46)
- [Granlibakken Tahoe - Tahoe City, CA](http://granlibakken.com/)
- [Required: Medical Form Part A & B](http://www.scouting.org/filestore/HealthSafety/pdf/680-001_AB.pdf)

<b>On both the NLS and DYLC pages, edit the sentences about meals to be the following:</b>

<i>With the exception of the Lake Tahoe NLS/DYLC, participants are on their own for their Friday evening meal. The first meal for the participants at the Los Angeles and Denver/Colorado Spring NLS/DYLC events will be breakfast on Saturday morning.</i>

<b>On both the NLS and DYLC pages, edit the sentence about timing to be the following:</b>

<i>Registration will begin at 5:00 p.m. Friday evening. First NLS session will start promptly at 8:00 p.m. and first DYLC session will start promptly at 7:30pm.  The seminar will conclude at 1:00 p.m. on Sunday afternoon after a closing recognition banquet lunch.  <b><u>Participation for the entire weekend through Sunday is required for recognition of completion of the NLS and DYLC courses; please do not register unless you are committed to attend Friday evening through Sunday in entirety.</u></b></i>

**Comment by MacRichards** [comment]
Updated and live on the website.

**Comment by rjrosamond** [comment]
Thanks for the super quick turnaround, Mac!  A couple more edits I just realized we should make...

Under each date, for the first bullet point that says "NLS & DYLC" please change it to "NLS (max capacity 64) & DYLC (max capacity 36)"

For the "Register" bullet point links, let's make them each say "Register Here, then pay your council/lodge afterward"

Those two changes should alleviate numerous questions I got this past year, hopefully!

**Comment by MacRichards** [comment]
All updated. Let us know if you need anything else changed.

**Comment by rjrosamond** [comment]
Looks great.  Thanks!  (closing request)

**Comment by rjrosamond** [comment]
On the NLS page, please remove the following sentence from the first paragraph:

"The weekend format is designed to complement the longer, more detailed Wood Badge and National Youth Leader Training (NYLT) Programs."

Also please replace any instance of the old NLS logo with this new one.
![2018 nls logo](https://user-images.githubusercontent.com/4088337/34512505-ce5990ce-f017-11e7-9085-86b884eb356c.png)

Thanks!

**Comment by MacRichards** [comment]
Sorry, this took so long to update. Totally fell off my radar. All of the changes have been made. Let me know if you find any hidden NLS logos I didn't find all I'll replace them.
