### ISSUE TITLE
styling issue on frontpage

### ISSUE THREAD

**Issue by bbodenmiller** [OAWest/western.oa-bsa.org#139]
Looks to be a styling issue on the frontpage

![image](https://user-images.githubusercontent.com/1192780/38170422-1a965e4c-353a-11e8-98f5-a6a91a3464b5.png)

**Comment by InfamousStarFox** [comment]
Thanks. The issue was with isotope grid: http://isotope.metafizzy.co/ rendering the post layout before the images finished loading.

For future reporting of theme errors, please refer to the template's GitHub page here: https://github.com/OAWest/wp-theme
