### ISSUE TITLE
Continual Refresh /about-us/contact-us.html

### ISSUE THREAD

**Issue by InfamousStarFox** [OAWest/western.oa-bsa.org#62]
All contact forms are stuck in an infinite loop of refreshing the iframe

**Comment by blove** [comment]
I can't seem to duplicate this issue. Do you have a URL? If I go to http://western.oa-bsa.org/about-us/contact-us.html then I get an error message, likely because the member id is not specified.

**Comment by InfamousStarFox** [comment]
You need to access the page by clicking a link to contact a leadership profile. Here is an example http://western.oa-bsa.org/about-us/contact-us.html?member_id=rttJ4hl1UX0edED1pWu8hwI1%2Fms9jXP7RhtS7VCd1YrDLEpU204Nx8jOxpHSvmNpOyVwRAtAMDykf6Nsnvg%2Bms

**Comment by blove** [comment]
Ahh, I see the issue when I open the console in the development tools. It looks like it is trying to get the nophoto.gif file, which is returning a 404.

**Comment by InfamousStarFox** [comment]
Ah! That's why it started appearing after we switched from the staging site to live. I'll re-upload the photo when I get home.

**Comment by InfamousStarFox** [comment]
No photo replacement placeholder image has been created
