### ISSUE TITLE
Add 2017 NLS & DYLC Dates

### ISSUE THREAD

**Issue by rjrosamond** [OAWest/western.oa-bsa.org#70]
Please add the following dates and locations to the NLS page:

May 5-7, 2017
Camp Tracy
Salt Lake City, UT
https://www.saltlakescouts.org/new-scout-camp

October 6-8, 2017
Camp Kuratli at Trestle Glen
Portland, OR
http://www.campkuratli.com/

November 10-12, 2017
(NLS only, no DYLC)
Tama Hills Recreation Area
Tokyo, Japan
http://www.yokotasupport.com/tama-hills/

Please add the following dates and locations to the DYLC page:

May 5-7, 2017
Camp Tracy
Salt Lake City, UT
https://www.saltlakescouts.org/new-scout-camp

October 6-8, 2017
Camp Kuratli at Trestle Glen
Portland, OR
http://www.campkuratli.com/

**Comment by blove** [comment]
@rjrosamond should we also deprecate/remove the NLATS page?

**Comment by rjrosamond** [comment]
Not yet. For now, let's just add verbiage that NLATS has been replaced by
DYLC, and refer people to that page. Thanks.

Rob

**Comment by blove** [comment]
For further clarification, should we remove the information on the NLATS page and just refer them to DYLC, or should we simply add an alert that directs people to the DYLC page at the top of the NLATS page (leaving the existing content below)?

**Comment by rjrosamond** [comment]
Let's add an alert and leave the existing content... because DYLC is still
in "pilot" phase it has not been officially adopted by the national
committee as a permanent replacement to NLATS.  It looks like it will be,
though we don't know that with 100% certainty yet.

Rob

**Comment by blove** [comment]
Got it, thanks Rob.

**Comment by blove** [comment]
This has been completed in PR #85
