### ISSUE TITLE
Update NLS page

### ISSUE THREAD

**Issue by rjrosamond** [OAWest/western.oa-bsa.org#93]
Please update the text at the top of the NLS page (all text above the dates) to the following:

The National Leadership Seminar (NLS) is a weekend training program focusing on leadership development. Run by the Region Chief and his Advisers, it provides an in-depth look at leadership skills and techniques. An NLS discusses how these skills can be applied in your role in the OA and in other aspects of your life. The National Leadership Seminar is a weekend conference on the skills and attributes of leadership. It is intended primarily to enhance the leadership skills of the Order of the Arrow’s key youth and adult members as they seek to improve their services to the Boy Scouts of America and the greater community. The weekend format is designed to complement the longer, more detailed Wood Badge and National Youth Leader Training (NYLT) Programs. Near the end of the seminar, participants make a contract with themselves to apply the skills studied in the seminar on projects in their lodge, council, and community.

Registration will begin at 5:00 p.m. Friday evening. First session will start promptly at 8:00 p.m. The seminar will conclude at 1:00 p.m. on Sunday afternoon after a closing recognition banquet lunch.

Participants are on their own for their Friday evening meal. The first meal for the participants will be breakfast on Saturday morning.

Adults age 21 and older are eligible to attend the Developing Youth Leadership Conference (DYLC) and do not necessarily need to have previously attended NLS but it is recommended. Adults who are currently or will soon hold a lodge-level or chapter-level adviser position are encouraged to attend DYLC. The NLS training is open to anyone seeking to hone their leadership skills applicable to Scouting as well as daily life. Adults who are unsure which might be best for them should talk to their lodge adviser for guidance or e-mail training@western.oa-bsa.org.

--------------------------------
Update the Registration section with the following text:

All participants must register themselves using the online registration links above. The national OA office will bill councils for all registrations. Participants are responsible for paying their lodge directly for the NLS or DYLC registration fees. Some lodges and sections provide scholarships; check with your local lodge chief or lodge adviser for details and specific instructions on submitting your payment, if applicable.

------------------------------
Update the Cancellation section with the following text:

Cancellation requests must be submitted to the Western Region Training Coordinator via e-mail at training@western.oa-bsa.org. The participant’s council will not be billed for the seminar fees if the cancellation request is received at least 21 days prior to the start of the event. Within 21 days of the event, registrations are transferable to others who are not already registered, but fees will still be billed in full. To transfer a registration, e-mail registration@western.oa-bsa.org for instructions and the name of the replacement. NLS participants can be swapped for DYLC participants and vice versa, youth or adult.

Don’t Forget: All participants need to bring a sleeping bag and uniform to the event.

**Comment by blove** [comment]
@rjrosamond I am working on this now. The only change I would suggest is to use the nls@western.oa-bsa.org email address instead of training@western.oa-bsa.org. I have created separate forwarders for NLS and DLYC that forwards to the respective adult volunteers.

**Comment by rjrosamond** [comment]
I would like to keep it as training@ because we get a variety of questions
that pertain to both courses and the messages are often from lodge
advisers.  Since I am the one handling registration and event logistics for
both NLS and DYLC, I need to see both anyway and then I reply-all so the
DYLC coordinator is always in the loop.  We tag-team responding to mail at
the training@ alias depending on the question.

nls@ is specifically for NLS contract submissions which goes to Adam
Sommers our Contract Completion Coordinator and his adviser, plus me as
backup.

Thanks!


Rob

**Comment by blove** [comment]
@rjrosamond ok, sounds good. Should we update the committee page to use the single training@western.oa-bsa.org email forwarder as well? Right now we have it using the individual ones: http://localhost:4000/leadership/training/

**Comment by rjrosamond** [comment]
Yes, should update the committee page to only use
training@western.oa-bsa.org for both NLS and DYLC.  Thanks.


Rob

**Comment by blove** [comment]
Ok, all set Rob.
