### ISSUE TITLE
Revised May 5-7 DYLC price and location

### ISSUE THREAD

**Issue by rjrosamond** [OAWest/western.oa-bsa.org#97]
The May 5-7 DYLC in Salt Lake City has had a price increase from $150 to $190 and includes 2 nights stay at the hotel.  The price for the NLS remains the same at $150 and will be held entirely at Camp Tracy.

DYLC itself is being moved to the Embassy Suites in West Valley City, UT.  We need to make this distinction on both the DYLC and NLS pages.  Here's the exact location/address of the hotel: http://embassysuites3.hilton.com/en/hotels/utah/embassy-suites-by-hilton-salt-lake-west-valley-city-SLCSMES/index.html

Let me know if you have any questions about this update.  Thanks!

**Comment by blove** [comment]
@rjrosamond this has been updated and pushed live to the website: http://western.oa-bsa.org/program/training/dylc/

Do you think we should also add a new post to the homepage?

**Comment by rjrosamond** [comment]
Not quite yet, as we may have a few more updates to make to the DYLC page
first before we would want to push any major communications on the home
page.

Rob
